"""Recovery-verification value objects (Phase 5F).

*"Execution succeeded"* does **not** mean *"the system recovered"*. Phase 5F adds
a separate, deterministic, evidence-based verification step between ``EXECUTED``
and the terminal ``RECOVERED`` / ``RECOVERY_FAILED`` verdict.

Nothing in this module performs I/O, runs a subprocess, or reasons with an LLM.
A :class:`HealthSnapshot` is **untrusted data** — its ``detail`` string is
recorded (redacted) for a human reader and is never parsed or executed.
"""

from __future__ import annotations

import secrets
from datetime import datetime
from enum import StrEnum

from pydantic import BaseModel, ConfigDict, Field

VERIFICATION_ID_RE = r"^ver_[0-9a-f]{16}$"

VERIFIER_VERSION = "1"
"""Bump on any change to the check set or the evaluation logic so a persisted
verification can be tied to the exact verifier that produced it (mirrors
``POLICY_VERSION``)."""

VERIFIER_TYPE_LOCAL = "DETERMINISTIC_LOCAL"
"""The only verifier backend in Phase 5F — deterministic, in-process, observes a
simulated health signal. A real-infrastructure probe is a deliberate future item
and is intentionally not enumerated here (fail closed)."""


def new_verification_id() -> str:
    return f"ver_{secrets.token_hex(8)}"


class VerificationStatus(StrEnum):
    """Status of a single recovery-verification attempt (Phase 5F).

    Distinct from :class:`~remediation_controller.domain.enums.RemediationStatus`:
    ``RECOVERED`` ↔ remediation ``RECOVERED``; ``RECOVERY_FAILED`` ↔ remediation
    ``RECOVERY_FAILED``; ``STARTED`` ↔ remediation ``VERIFYING``.
    """

    STARTED = "STARTED"
    RECOVERED = "RECOVERED"
    RECOVERY_FAILED = "RECOVERY_FAILED"


class HealthStatus(StrEnum):
    """The probe's own synthesised assessment. **Informational only** — the
    verifier applies its *own* thresholds and never trusts this field for the
    verdict (same principle as the policy engine ignoring ``proposal.risk_level``)."""

    HEALTHY = "HEALTHY"
    DEGRADED = "DEGRADED"
    UNHEALTHY = "UNHEALTHY"


class HealthSnapshot(BaseModel):
    """One deterministic observation of a target service's health.

    Treated as untrusted data everywhere downstream: ``detail`` is a string a
    monitored service could control, so it is redacted before storage and never
    interpreted.
    """

    model_config = ConfigDict(frozen=True, extra="forbid")

    service: str
    environment: str
    status: HealthStatus
    ready: bool
    running: bool
    replicas_available: int = Field(ge=0)
    error_rate: float = Field(ge=0.0, le=1.0)
    success_rate: float = Field(ge=0.0, le=1.0)
    latency_p95_ms: float = Field(ge=0.0)
    detail: str = Field(default="", max_length=2000)
    observed_at: datetime


class RecoveryCheck(BaseModel):
    """One deterministic pass/fail evaluation against a verifier-owned threshold.

    ``observed`` / ``threshold`` / ``detail`` are short operational strings for a
    human reader — generated by deterministic code, redacted, never executed.
    """

    model_config = ConfigDict(frozen=True, extra="forbid")

    name: str = Field(max_length=64)
    passed: bool
    observed: str = Field(max_length=200)
    threshold: str = Field(max_length=200)
    detail: str = Field(default="", max_length=500)


class RecoveryOutcome(BaseModel):
    """What the :class:`RecoveryVerifier` returns — the verdict plus its evidence.

    The service assembles the persisted :class:`VerificationResult` from this
    plus the ids / config snapshot it already holds.
    """

    model_config = ConfigDict(frozen=True, extra="forbid")

    status: VerificationStatus
    checks: tuple[RecoveryCheck, ...]
    attempts: int = Field(ge=1)
    first_healthy_at: datetime | None = None
    failure_reason: str | None = Field(default=None, max_length=1000)
    probe_status: HealthStatus
    verifier_type: str = Field(max_length=32)
    verifier_version: str = Field(max_length=16)
    started_at: datetime
    completed_at: datetime

    @property
    def recovered(self) -> bool:
        return self.status is VerificationStatus.RECOVERED

    @property
    def checks_passed(self) -> int:
        return sum(1 for c in self.checks if c.passed)


class VerificationResult(BaseModel):
    """The persisted / API shape of one recovery verification (Phase 5F).

    Immutable. Mapped to the ``remediation_verifications`` row. There is no field
    anywhere on this model that can hold a command / script / shell string.
    """

    model_config = ConfigDict(frozen=True, extra="forbid")

    verification_id: str = Field(pattern=VERIFICATION_ID_RE)
    remediation_id: str
    execution_id: str
    status: VerificationStatus
    verifier_type: str = Field(max_length=32)
    verifier_version: str = Field(max_length=16)
    attempts: int = Field(ge=0)
    checks: tuple[RecoveryCheck, ...] = ()
    failure_reason: str | None = Field(default=None, max_length=1000)
    timeout_seconds: int = Field(ge=1, le=3600)
    poll_interval_seconds: float = Field(gt=0.0, le=600.0)
    metadata: dict[str, str | int | bool] = Field(default_factory=dict)
    started_at: datetime
    completed_at: datetime | None = None

    @property
    def recovered(self) -> bool:
        return self.status is VerificationStatus.RECOVERED


__all__ = [
    "VERIFICATION_ID_RE",
    "VERIFIER_TYPE_LOCAL",
    "VERIFIER_VERSION",
    "HealthSnapshot",
    "HealthStatus",
    "RecoveryCheck",
    "RecoveryOutcome",
    "VerificationResult",
    "VerificationStatus",
    "new_verification_id",
]
