"""The structured, machine-readable policy result.

A :class:`PolicyDecision` is deterministic (identical proposal + context + config
=> identical decision), serializable, and carries only concise reason codes —
never natural-language reasoning and never private model chain-of-thought.
"""

from __future__ import annotations

from datetime import datetime

from pydantic import BaseModel, ConfigDict, Field

from remediation_controller.policy.codes import PolicyOutcome, PolicyReasonCode


class PolicyViolation(BaseModel):
    """One rule failure. ``detail`` is a short operational string for a human
    reader; it is generated by deterministic code, not by an LLM."""

    model_config = ConfigDict(frozen=True, extra="forbid")

    code: PolicyReasonCode
    rule: str = Field(max_length=64)
    detail: str = Field(max_length=500)


class PolicyDecision(BaseModel):
    """The outcome of :meth:`PolicyEngine.evaluate`."""

    model_config = ConfigDict(frozen=True, extra="forbid")

    outcome: PolicyOutcome
    reason_codes: tuple[PolicyReasonCode, ...]
    violations: tuple[PolicyViolation, ...] = ()
    policy_version: str
    evaluated_rules: tuple[str, ...]
    evaluated_at: datetime

    @property
    def allowed(self) -> bool:
        return self.outcome is PolicyOutcome.ALLOW

    @property
    def approved_for_human_review(self) -> bool:
        """``True`` iff policy passed. Explicitly *not* "approved for execution" —
        a human approval is still required (:data:`PolicyReasonCode.APPROVAL_REQUIRED`
        is always in :attr:`reason_codes` here)."""

        return self.allowed
