"""Strongly typed, machine-validatable Phase 4 contracts.

These are Pydantic (not dataclasses like ``incident_correlator.domain``) on
purpose: they are simultaneously the LLM structured-output target, the REST API
response, the persisted document, and the thing the deterministic validation
layer (:mod:`rca_agent.validation`) checks. See ADR-019.

Every ``*_ids`` list references :attr:`Evidence.id` values collected *during this
investigation*. ``rca_agent.validation`` rejects dangling references before a
report is persisted or returned — the LLM cannot invent evidence.
"""

from __future__ import annotations

from datetime import datetime
from typing import Any, Literal

from pydantic import BaseModel, ConfigDict, Field

from rca_agent.domain import (
    Confidence,
    EvidenceSourceType,
    FindingType,
    HypothesisVerdict,
    InvestigationStatus,
    InvestigationTrigger,
    RecommendedActionType,
    StepKind,
    TrustLevel,
)
from rca_agent.limits import ResourceLimits

_EV_ID = r"^ev_[a-z0-9_]+$"
_FI_ID = r"^fi_[a-z0-9_]+$"
_HY_ID = r"^hy_[a-z0-9_]+$"


class Evidence(BaseModel):
    """One normalized, immutable piece of evidence collected by a read-only tool.

    ``id`` is assigned deterministically by the collector (Sub-phase 4B), never
    by the LLM. ``summary`` is generated by deterministic code, not the model.
    ``content`` is the tool's normalized payload and is treated as untrusted
    data everywhere downstream.
    """

    model_config = ConfigDict(frozen=True)

    id: str = Field(pattern=_EV_ID)
    source_type: EvidenceSourceType
    source_reference: str = Field(max_length=500)
    trust_level: TrustLevel
    tool_name: str = Field(max_length=64)
    service: str | None = Field(default=None, max_length=128)
    summary: str = Field(max_length=2000)
    content: dict[str, Any] = Field(default_factory=dict)
    observed_at: datetime | None = None
    collected_at: datetime


class Finding(BaseModel):
    model_config = ConfigDict(frozen=True)

    id: str = Field(pattern=_FI_ID)
    type: FindingType
    statement: str = Field(max_length=2000)
    evidence_ids: list[str] = Field(default_factory=list)
    confidence: Confidence = Confidence.UNKNOWN


class Hypothesis(BaseModel):
    model_config = ConfigDict(frozen=True)

    id: str = Field(pattern=_HY_ID)
    statement: str = Field(max_length=2000)
    supporting_evidence_ids: list[str] = Field(default_factory=list)
    contradicting_evidence_ids: list[str] = Field(default_factory=list)
    assessment: str = Field(max_length=2000)
    verdict: HypothesisVerdict


class RootCause(BaseModel):
    model_config = ConfigDict(frozen=True)

    statement: str = Field(max_length=2000)
    confidence: Confidence
    evidence_ids: list[str]
    reasoning_summary: str = Field(max_length=4000)


class RecommendedAction(BaseModel):
    """A remediation *recommendation* for a human. Phase 4 never executes it.

    ``action_type`` is a closed enum and ``requires_human_approval`` is
    ``Literal[True]`` — structurally, this object cannot express or authorize an
    executable command. Phase 5 owns execution (ADR-003).
    """

    model_config = ConfigDict(frozen=True)

    action_type: RecommendedActionType
    target_service: str | None = Field(default=None, max_length=128)
    description: str = Field(max_length=2000)
    rationale: str = Field(max_length=2000)
    evidence_ids: list[str] = Field(default_factory=list)
    requires_human_approval: Literal[True] = True


class TimelineEntry(BaseModel):
    model_config = ConfigDict(frozen=True)

    at: datetime
    description: str = Field(max_length=1000)
    evidence_ids: list[str] = Field(default_factory=list)


class InvestigationStep(BaseModel):
    """One entry in the operational investigation trace. Concise operational
    reasoning only — never private model chain-of-thought."""

    model_config = ConfigDict(frozen=True)

    seq: int = Field(ge=1)
    kind: StepKind
    phase: InvestigationStatus
    description: str = Field(max_length=2000)
    tool_name: str | None = Field(default=None, max_length=64)
    evidence_ids: list[str] = Field(default_factory=list)
    at: datetime


class InvestigationMetadata(BaseModel):
    model_config = ConfigDict(frozen=True)

    mode: Literal["mock", "live"]
    llm_provider: str | None = None
    model: str | None = None
    started_at: datetime
    completed_at: datetime
    duration_seconds: float = Field(ge=0)
    tool_call_count: int = Field(ge=0)
    step_count: int = Field(ge=0)
    evidence_count: int = Field(ge=0)
    termination_reason: str = Field(max_length=200)
    limits: ResourceLimits


class RCAReport(BaseModel):
    """The structured, evidence-grounded output of an investigation.

    ``status`` is restricted to the two analytical terminal outcomes; a
    ``FAILED`` / ``TIMED_OUT`` investigation has no report (or a partial one
    surfaced elsewhere). ``root_cause is None`` is a valid, honest result.
    """

    incident_id: str = Field(max_length=40)
    investigation_id: str = Field(max_length=40)
    status: Literal[InvestigationStatus.COMPLETED, InvestigationStatus.INSUFFICIENT_EVIDENCE]
    summary: str = Field(max_length=4000)
    severity: str | None = Field(default=None, max_length=16)
    affected_services: list[str] = Field(default_factory=list)
    timeline: list[TimelineEntry] = Field(default_factory=list)
    findings: list[Finding] = Field(default_factory=list)
    hypotheses: list[Hypothesis] = Field(default_factory=list)
    root_cause: RootCause | None = None
    contributing_factors: list[Finding] = Field(default_factory=list)
    recommended_action: RecommendedAction
    evidence: list[Evidence] = Field(default_factory=list)
    overall_confidence: Confidence = Confidence.UNKNOWN
    uncertainty: str = Field(max_length=4000)
    unavailable_evidence_sources: list[str] = Field(default_factory=list)
    investigation_metadata: InvestigationMetadata


class Investigation(BaseModel):
    """The persisted investigation entity (the row view, minus children)."""

    id: str = Field(max_length=40)
    incident_id: str = Field(max_length=40)
    status: InvestigationStatus
    trigger: InvestigationTrigger
    mode: Literal["mock", "live"]
    model: str | None = None
    termination_reason: str | None = None
    tool_call_count: int = 0
    step_count: int = 0
    evidence_count: int = 0
    overall_confidence: Confidence = Confidence.UNKNOWN
    started_at: datetime | None = None
    completed_at: datetime | None = None
    created_at: datetime
    updated_at: datetime


# Evidence source types that have a real backend in this repository today.
AVAILABLE_EVIDENCE_SOURCES: frozenset[EvidenceSourceType] = frozenset(
    {
        EvidenceSourceType.INCIDENT,
        EvidenceSourceType.ANOMALY,
        EvidenceSourceType.METRIC,
        EvidenceSourceType.SERVICE_HEALTH,
        EvidenceSourceType.RELATED_INCIDENT,
    }
)
UNAVAILABLE_EVIDENCE_SOURCES: frozenset[EvidenceSourceType] = frozenset(
    s for s in EvidenceSourceType if s not in AVAILABLE_EVIDENCE_SOURCES
)
